version: "3.8"
services:
  mysql:
    image: mysql:8
    container_name: mysql-c
    ports:
      - 127.0.0.1:${MYSQL_PORT}:3306
    networks:
      - lemp-network
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_NAME}
    restart: always

  adminer:
    image: adminer:4.8.1-standalone
    container_name: adminer-c
    ports:
      - 0.0.0.0:${ADMINER_PORT}:8080
    networks:
      - lemp-network
    restart: always
    depends_on:
      - mysql

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php-c
    ports:
      - 127.0.0.1:${PHP_PORT}:9000
    networks:
      - lemp-network
    volumes:
      - ./www:/var/www/html
    env_file: ./.env
    restart: always
    depends_on:
      - mysql

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx-c
    ports:
      - 0.0.0.0:${LEMP_PORT}:80
    networks:
      - lemp-network
    volumes:
      - ./nginx/.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/html
    restart: always
    depends_on:
      - php

volumes:
  mysql-data:
    name: lemp-mysql-data

networks:
  lemp-network:
    driver: bridge
